/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorNode: typeof import('./src/components/architecture/nodes/ActorNode.vue')['default']
    AgentSequence: typeof import('./src/components/architecture/AgentSequence.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BudgetTable: typeof import('./src/components/BudgetTable.vue')['default']
    ChatBubble: typeof import('./src/components/ChatBubble.vue')['default']
    CloudNode: typeof import('./src/components/architecture/nodes/CloudNode.vue')['default']
    ContextDataFlow: typeof import('./src/components/architecture/ContextDataFlow.vue')['default']
    DatabaseNode: typeof import('./src/components/architecture/nodes/DatabaseNode.vue')['default']
    DecisionNode: typeof import('./src/components/architecture/nodes/DecisionNode.vue')['default']
    EvaluationSystem: typeof import('./src/components/architecture/EvaluationSystem.vue')['default']
    ExportMenu: typeof import('./src/components/ExportMenu.vue')['default']
    GroupNode: typeof import('./src/components/architecture/nodes/GroupNode.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ItineraryPrintView: typeof import('./src/components/ItineraryPrintView.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NModal: typeof import('naive-ui')['NModal']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RagPipeline: typeof import('./src/components/architecture/RagPipeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceNode: typeof import('./src/components/architecture/nodes/ServiceNode.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SpotItem: typeof import('./src/components/SpotItem.vue')['default']
    SystemArchitecture: typeof import('./src/components/architecture/SystemArchitecture.vue')['default']
  }
}
