/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorNode: typeof import('./src/components/architecture/nodes/ActorNode.vue')['default']
    AgentSequence: typeof import('./src/components/architecture/AgentSequence.vue')['default']
    BudgetTable: typeof import('./src/components/BudgetTable.vue')['default']
    ChatBubble: typeof import('./src/components/ChatBubble.vue')['default']
    CloudNode: typeof import('./src/components/architecture/nodes/CloudNode.vue')['default']
    ContextDataFlow: typeof import('./src/components/architecture/ContextDataFlow.vue')['default']
    ConversationDrawer: typeof import('./src/components/ConversationDrawer.vue')['default']
    DatabaseNode: typeof import('./src/components/architecture/nodes/DatabaseNode.vue')['default']
    DecisionNode: typeof import('./src/components/architecture/nodes/DecisionNode.vue')['default']
    EvaluationSystem: typeof import('./src/components/architecture/EvaluationSystem.vue')['default']
    ExportMenu: typeof import('./src/components/ExportMenu.vue')['default']
    GroupNode: typeof import('./src/components/architecture/nodes/GroupNode.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ItineraryPrintView: typeof import('./src/components/ItineraryPrintView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceNode: typeof import('./src/components/architecture/nodes/ServiceNode.vue')['default']
    SpotItem: typeof import('./src/components/SpotItem.vue')['default']
    SystemArchitecture: typeof import('./src/components/architecture/SystemArchitecture.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
